dist: trusty
services: docker
language: php

sudo: required

env:
  global:
    - setup=basic
    - APP_ENV=testing

matrix:
  include:
    - php: 7.1
      env:
        phpunit: false
        distro: arch
        run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"

before_install:
  - travis_retry composer self-update
  - if [[ -n $distro ]]; then travis_retry docker pull thenodi/docker-${distro}-valet:latest; fi

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - if [[ $phpunit = true ]]; then vendor/bin/phpunit; fi

  # Start the container in detached mode
  - >
    if [[ -n $distro ]]; then
      CONTAINER_ID=$( \
          docker run --detach \
              --volume="${PWD}":/workspace \
              -e "REPOSITORY=/workspace" \
              --dns=8.8.8.8 \
              --dns=8.8.4.4 \
              --dns-opt='options single-request' \
              --sysctl net.ipv6.conf.all.disable_ipv6=1 \
              ${run_opts} \
              thenodi/docker-${distro}-valet:latest
      );
    fi

  # Debug
  - dig google.com
  - dig mirrors.kernel.org

  # Prepare the container
  - if [[ -n $distro ]]; then docker exec -it $CONTAINER_ID sudo pacman -Sy --debug; fi

  # Run functional tests
  - if [[ -n $distro ]]; then docker exec -it -u valet $CONTAINER_ID /workspace/tests/Functional/run.sh; fi
